export const startPosition : MoveFromBack = 
    {
        "move": "",
        "annotation": "",
        "position": [
            [
                "brn",
                "bnn",
                "bbn",
                "bqn",
                "bkn",
                "bbn",
                "bnn",
                "brn"
            ],
            [
                "bpn",
                "bpn",
                "bpn",
                "bpn",
                "bpn",
                "bpn",
                "bpn",
                "bpn"
            ],
            [
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00"
            ],
            [
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00"
            ],
            [
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00"
            ],
            [
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00",
                "00"
            ],
            [
                "wpn",
                "wpn",
                "wpn",
                "wpn",
                "wpn",
                "wpn",
                "wpn",
                "wpn"
            ],
            [
                "wrn",
                "wnn",
                "wbn",
                "wqn",
                "wkn",
                "wbn",
                "wnn",
                "wrn"
            ]
        ],
        "gameId": "1"
    }
